AWSTemplateFormatVersion: '2010-09-09'
Resources:
  LambdaRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName:
        Fn::Sub: lambda-role
      AssumeRolePolicyDocument:
        Statement:
          - Action:
            - sts:AssumeRole
            Effect: Allow
            Principal:
              Service:
              - lambda.amazonaws.com
        Version: 2012-10-17
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AWSLambdaExecute
        - arn:aws:iam::aws:policy/AmazonS3FullAccess
        - arn:aws:iam::aws:policy/AmazonDynamoDBFullAccess
  LambdaFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName:
        Fn::Sub: findVanityNumbers
      Runtime: nodejs14.x
      Code: lambda/
      Handler: index.handler
      Timeout: 20
      Environment:
        Variables:
          TABLE_NAME: VanityNumbers
      Role:
        Fn::GetAtt: ["LambdaRole", "Arn"]
  VanityNumberTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: VanityNumbers
      AttributeDefinitions:
        -
          AttributeName: phoneNumber
          AttributeType: S
      KeySchema:
        -
          AttributeName: phoneNumber
          KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
